matrix:
    include:
        - os: linux
            dist: xenial
            sudo: required
            language: c
            install: sudo apt-get update \
                sudo apt-get install -y \
                autoconf \
                automake

script: 
    - make test
    - make
    - ./bin/antman -h
    - make clean