language: c

matrix:
    include:

    # Build for 64-bit Linux
    - os: linux
        dist: xenial
        sudo: required
        install: sudo apt-get update \
            sudo apt-get install -y \
            autoconf \
            automake

script: 
    - make test
    - make
    - ./bin/antman -h
    - make clean