dist: xenial
sudo: required
dist: bionic
language: c
compiler:
  - gcc

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          update: true
          packages:
          - automake
          - fswatch
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      before_install:
        - sudo apt-get update -qq
        - sudo ./scripts/install-fswatch.sh
        - sudo ldconfig

script:
  - ./autogen.sh
  - ./configure CPPFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"
  - make
  - make check
  - sudo make install
  - ./run-antman-tests.py
  - make clean
