dist: xenial
sudo: required
dist: bionic
language: c
compiler:
  - gcc

matrix:
  include:
    - os: osx
      osx_image: xcode11
      addons:
      homebrew:
        packages:
          - fswatch
  include:
    - os: linux
      addons:
        apt:
          packages:
          - fswatch

script:
  - make
