dist: xenial
sudo: required
language: c
compiler: gcc

jobs:
    include:
      - os: linux
        install: sudo apt-get update \
        sudo apt-get install -y \
        autoconf \
        automake
        script:
        - make
        - ./bin/antman -h
        - make clean

      - os: osx
        script:
        - make
        - ./bin/antman -h
        - make clean