dist: xenial
sudo: required
dist: bionic
language: c
compiler:
  - gcc

matrix:
  include:
    - os: osx
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y gettext
        - sudo apt-get install -y autopoint

script:
  - make
