site_name: ANTMAN
repo_url: https://github.com/will-rowe/antman
site_author: Will Rowe
nav:
  - Home: index.md
  - Installation: installation.md
  - The Configuration File: the-config.md
theme: readthedocs
