sudo: required
dist: xenial
language: cpp

matrix:
  include:
  - compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
        packages:
          - clang-3.7
    env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gettext
  - sudo apt-get install -y autopoint

script: ./autogen.sh && ./configure && make
